pagarme/pagarme-js

lib/client/strategies/api.js
lib/client/strategies/encryption.js
lib/client/strategies/index.js
lib/resources/index.spec.js

This PR fixes the current broken encryption_key validation. It also cleans and moves away validation functions from strategies/index.js to make it more clean and concise.

Fix encryption key validation and move validation responsability to strategies

---

lib/client/strategies/api.js
lib/client/strategies/encryption.js
lib/resources/index.spec.js

Adds a warning when client.connect can't communicate with pagarme's
server. Now the client will only log a warning instead of throwing
an error if it fails to send the key verification request. It will
still give an error if the request is successfull and the key is invalid
* This PR is based on the https://github.com/pagarme/pagarme-js/pull/40 branch because the changes are built on top of that one.

strategies: add better error handling when offline

---

lib/validations/index.test.js
lib/validations/validators/card/index.js

Proviously the card validator would not check if all card props were
sent. Now an error will be thrown with the missing props information.

validations: fix card input validation

---

lib/resources/transactions.js
lib/resources/transactions.spec.js

Both `refund` and `capture` were not passing the `body` forward.

transactions: fix refund and capture body

---

lib/resources/transactions.js

This link doesn't exist in the new API docs. We have a lot of endpoints
that are missing in the new API docs so this only deletes the wrong
link. We need to address the missing parts but that's a different issue.

transactions: fix `update` body link doc

---

lib/validations/index.test.js
lib/validations/validators/cnpj-and-cpf.js
lib/validations/validators/cnpj-and-cpf.spec.js
lib/validations/validators/index.js

Previously the CPF and CNPJ validations would wrongly validate
each other. I've added a length validation to stop that from happening.

validations: add length validation for cpf/cnpj

---

lib/resources/invites.js
lib/resources/recipients.js
lib/resources/subscriptions.js
lib/resources/transactions.js
lib/resources/transfers.js
lib/resources/user.js

Some of the endpoints that had `all` alias were missing docs for it.
This adds the missing docs.

resources: add `all` alias missing docs

---

lib/resources/index.spec.js

The e2e tests that tested pagarme.connect were passing when they shouldn't.
This was caused by a PR that changed the error messages when connect failed.
If we intend to change these messages again we should make a new error type
to avoid having to fix this again.

tests: fix e2e tests

---

lib/resources/index.spec.js

It fixes the usage of process.env.API_KEY

Use api_key from temporary companies 

---

lib/request.js

As the SDK is agnostic with the payload's content, then it sounds reasonable to not have a payload validation - even the simplest.

Remove payload validation

---

lib/client/index.js

The connection example is using lower camel case to pass the keys, which in a real implementation won't work.
Resolves: #75

docs: fix client connection example

---

lib/validations/index.spec.js
lib/validations/validators/card/getBrand.js

This fix some unexpected validations errors that was happening due to
variations in card number, like when card number was type number instead
of string and when card number was one-digit number and  didn't match
any brand.
- Fix card number validations to receive card_number typed as a number
instead of string
- Fix brand validation to be unknown when card number is one-digit
and don't match any brand
Resolves: #78

validations: fix some unexpected validations errors

---

.npmignore

To avoid problems with projects using babel 6.
#82

npmignore: add babelrc to npmignore

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Closes #69 and closes #70 
I tried to keep the templates consistent between what I saw in other Pagarme's projects, more details can be found in the commit messages! 
Some other considerations:
- On contribution guide I wrote the start commands using `yarn` instead of `npm` as there's already a _yarn.lock_ in this project, if this is not what you recommend, I can change it
- The email for reporting abusive behavior and security flaws was dashboard@pagar.me, as it is the only one I know for reaching you guys (besides _code@pagar.me_, but I think this one is for sending resumes, right?)

Feature/add GitHub files

---

lib/resources/chargebacks.js
lib/resources/chargebacks.spec.js
lib/resources/index.js
lib/routes.js

This adds the missing `GET /chargebacks` route.

Add Chargebacks route

---

lib/validations/validate/cnpjAndCpf.js
lib/validations/validate/cnpjAndCpf.spec.js

instead of using an array of blacklisted cpf's uses a regex instead
closes #60 

cpf-validation: replace blacklist for regex

---

lib/resources/chargebackOperations.js
lib/resources/chargebackOperations.spec.js
lib/resources/gatewayOperations.js
lib/resources/gatewayOperations.spec.js
lib/resources/index.js
lib/routes.js

Adds the chargeback operations route and fix GatewayOperation's route and some of its docs messages.

Add chargeback operations route and fix some errors in GatewayOperations

---

lib/resources/index.js
lib/resources/status.js
lib/resources/status.spec.js
lib/routes.js

This adds `/status` route to library, allowing users to find the environment
and check for service status too.

Add status route

---

.gitignore
lib/client/strategies/login.js

This allows specifying `environment: 'live'` on login authentication
strategy, which sets the `X-Live: 1` header in all requests sent by
the client, allowing the client to issue requests to live environment.

Allow creating a client with live environment when using login strategy

---

lib/request.js

Adds `error.response.status` to get error response status code.
This is needed as we don't have good error keys on body.

Add status to error.response

---

lib/resources/subscriptions.js
lib/resources/subscriptions.spec.js
lib/routes.js

This PR add the subscriptions settle charge feature to the SDK, as it is on our documentation(https://docs.pagar.me/reference#transa%C3%A7%C3%B5es-em-uma-assinatura).
It also fixes issue #137 .

subscriptions: add settle charge feature

---

README.md

In multiple places of the repository the word `JavaScript` is spelled with the `'s'` character capitalized, however in the title of the README.md, it is not. This PR fixes the issue.

readme: make Javascript 's' be capitalized

---

lib/client/index.js
lib/resources/index.spec.js

This Pull request adds `.withVersion` method.
This method allows calling a request with a specific version with a chainable API.
example:
```js
client
.withVersion('2019-02-18')
.balanceOperations
.all()
```
When `withVersion` is called the `header` `X-PagarMe-Version` is set to the version passed as param and bound to resources to be called chainable.
resolves #154

add withVersion method

---

lib/resources/transfers.js
lib/resources/transfers.spec.js

Adiciona a possibilitade de passar parametros na request `client.transfers.limits`. Isso é necessário para consegui utilizar como esperado a rota `transfers/limits`.
resolves #165 
- verificar o novo teste que foi adicionado
- criar uma request pra `client.transfers.limits({ recipient_id: '<id do recebedor>' })
- verificar se os dados retornam como esperado

transfers: add params in limits request

---

lib/resources/payables.js
lib/resources/payables.spec.js
lib/routes.js

This PR adds a new subroute in payables which brings as result from API a payables summary by day.
Resolves #172
1 - Download and build this project.
2 - Create a yarn link using the command `yarn link`.
3 - In the Pilot project(using the branch [`refactor/balance-page`](https://github.com/pagarme/pilot/pull/1236)) use the generated link with the command `yarn link pagarme`.
4 - Acess the balance page and use the filter "A receber".

Add payables days route

---

lib/request.js

This PR solves a mistake made in the last version which was using `navigator` directly as a global variable, but this doesn't work in nodejs.
- Resolves #179 
1 - Download and build this branch
2 - Link this project using `yarn link``
3 - Use the generated link in a node project which uses pagarme-js
4 - Use the same link in a web application ex: [Pilot](https://github.com/pagarme/pilot)
Both projects must work correctly.

Refactor UserAgent usage

---

.eslintrc
lib/request.js
webpack.config.js

This PR solves a development mistake that was adding all the `package.json` into the production bundle.
- Resolves #182
1 - Download and build this branch
2 - Link this project using `yarn link`
3 - Use the generated link in a node project which uses pagarme-js
4 - Use the same link in a web application ex: [Pilot](https://github.com/pagarme/pilot)
Both projects must work correctly.

Refactor version origin

---

lib/resources/transactions.js
lib/resources/transactions.spec.js
lib/routes.js

Added route `reprocess` to transactions resource, this enables the library to reprocess transactions.
closes https://github.com/pagarme/pagarme-js/issues/196

transactions: add reprocess route

---

lib/client/strategies/login.js

Using any other authentication method (api_key, encryption_key and session_id), we can specify a `options` object. This allows us to change the API's base URL when doing tests locally, however, this `options` parameter is not being used when authenticating with `email` and `password`, which makes it impossible to use the `baseURL` option on frontend projects. This PR fixes that.
Resolves #207

Authentication - Add options to login

---

lib/resources/company.js

Fixes the company activate method. It should accept a `body` param, that contains the `token` parameter that will be used to activate the company.

company: fix activate request

---

lib/resources/acquirers.js
lib/resources/acquirers.spec.js
lib/routes.js

Adiciona a rota `/acquirer/:id/anticipation_delay/:delay`

Adiciona rota de antecipação em acquirer

---

lib/resources/index.js
lib/resources/onboardingAnswers.js
lib/resources/onboardingAnswers.spec.js
lib/resources/onboardingQuestions.js
lib/resources/onboardingQuestions.spec.js
lib/routes.js

Add the resources for the following routes:
- `GET /onboarding_question/:id`
- `GET /onboarding_answers`
- `POST /onboarding_answers`
- `DELETE /onboarding_answers/:id`
Issue: https://github.com/pagarme/credenciamento/issues/472
Related to: https://github.com/pagarme/credenciamento/issues/451
----
1. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-g:uide)

Adiciona as rotas de onboarding

---

lib/resources/onboardingAnswers.js
lib/resources/onboardingAnswers.spec.js
lib/routes.js

This PR changes the delete onboardingAnswer delete route from `DELETE /onboarding_answers/:id` to `DELETE /onboarding_answers?question_id=x`.
This changed is needed because it will simplify the logic that will be constructed for the onboarding-pages.
Related to https://github.com/pagarme/credenciamento/issues/482

onboardingAnswers: adjust delete route

---

lib/resources/company.js
lib/resources/company.spec.js
lib/routes.js

Este Pr adiciona a rota de `emailConfirmation` para company
- resolve https://github.com/pagarme/tecnologia-vendas/issues/833
- baixar a branch `add/emai-confirmation-route`
- Executar os tests
- Para Testar localmente
- Execute `npm run build`
- Execute `npm pack` isso irá gerar um pacote de arquivo em `.tgz` copie o path e cole no packjson.json do seu projeto ou use o exemplo abaixo
```json
// crie um arquivo package.json
{
"name": "test",
"version": "1.0.0",
"main": "index.js",
"license": "MIT",
"dependencies": {
"pagarme": "COLE O PATH GERADO DO ARQUIVO .tgz AQUI"
}
}
```
```js
// crie um arquivo index.js
const pagarme = require('pagarme')
pagarme
.client
.company
.emailConfirmation({
headers: {
'X-Live': 1,
}
}, { "email": "seu-email-para-testar@pagar.me" })
.then(() => …
```

routes: add emailConfirmation route

---

lib/resources/index.js
lib/resources/refunds.js
lib/resources/refunds.spec.js
lib/routes.js

To be able to search for and cancel refunds, we need the following routes:
- `GET /refunds`
- `POST /refunds/:id/cancel`
Although we won't use refund cancel route for now, on this pull request I am adding both
Resolves https://github.com/pagarme/pagarme-js/issues/261

Add refund routes

---

lib/resources/subscriptions.js
lib/resources/subscriptions.spec.js

Resolve o problema da issue https://github.com/pagarme/pagarme-js/issues/269
Com essa alteração será possível enviar os parâmetros `count` e `page` na rota `subscriptions/:id/transactions`
Dúvida: Preciso commitar os arquivos alterados com `yarn build`?

Permite enviar parâmetros na busca por transações de assinaturas

---

lib/resources/index.js
lib/resources/pix.js
lib/resources/pix.spec.js
lib/routes.js
package.json

Esse PR adiciona a rota `GET /pix/keys` e `POST /pix/keys`. Com ela, será possivel retornar todas as chaves ativas de uma company no serviço PIX e gerar novas chaves. 
- `client.pix.create({ recipient_id: 'abc' })`
- `client.pix.all()`

EXP-640 Adicionar rota /pix/keys ao pagarme-js

---

lib/resources/index.js
lib/resources/settlements.js
lib/resources/settlements.spec.js
lib/routes.js

Adicionado rota para trazer todos os settlements de um recipient

EXP-751 mapear rota GET /recipient/:id/settlements

---

lib/resources/settlements.js
lib/resources/settlements.spec.js
lib/routes.js

Esse PR adiciona a rota de contratos externos nas liquidações. Alteração no rota de `client.settlements()`  para `client.settlements.all()`.
- Verificar se as rotas `client.settlements.all()` está sendo chamado corretamente
- Verificar se as rotas `client.settlements.contracts.all()` está sendo chamado corretamente

EXP-767 mapear a rota GET /recipients/:recipientId/settlements/contracts 

---

.circleci/config.yml
package.json
yarn.lock

- Atualiza jsdoc para versão 3.6.7 para corrigir erros ao gerar docs com o node 12.
- Também atualiza CI para remover versões 6 e 8 do node que não funcionam com a nova versão do jsdoc.
- Adiciona versão 12 no CI.

[EXP-777] chore: bump jsdoc to 3.6.7

---

lib/client/strategies/index.js
lib/client/strategies/jwt.js

Esse PR tem o objetivo de criar uma nova estratégia de login utilizando o jwt + acocunt_id.
- buildar o projeto nesta branch.
- tentar fazer o login da seguinte forma:
`pagarme.client.connect({
jwt: 'jwt token aqui',
account_id: 'account id aqui'
})`
- Verificar que o login foi feito com sucesso e que é possível utilizar esses dados para fazer requests.
OBS: Explicações de como conseguir o token jwt e o account_id se encontram na issue do jira.

[EXP-787] Criar estratégia de login com jwt + account_id

---

lib/validations/index.spec.js

- O teste que testava a validação de card_expiration_date estava com uma uma data fixa e que fazia o teste só ser válido até mês passado. Agora ele sempre vai pegar o ano atual + 1
- Rodar os testes e ver se estão passando

fix: card_expiration_date validation test

---

lib/resources/subscriptions.js
lib/resources/subscriptions.spec.js

- Remove id do body da chamada subscriptions.findTransactions
- Linkar esse PR com o PR da pilot de detalhes de subscription
- Impersonar na pilot com uma company que tenha subscription
- verificar se a chamada da lista de transações funcionou corretamente

[EXP-1076] Remove id do body da chamada subscriptions.findTransactions
