lib/client/index.js

This PR improves our recursive binder and cleans up unused code.

client: refactor recursive options binder

---

lib/client/index.js
lib/client/strategies/api.js
lib/client/strategies/encryption.js
lib/client/strategies/login.js
lib/resources/index.spec.js

Add client.authentication variable after binding the option to the client, this is usefull for getting your session info when authenticating with email/password for example.

strategies: Add authentication info in bound client

---

README.md

Adds a link to our docs in the start of our readme file

readme: improve docs visibility

---

lib/resources/index.js
lib/resources/zipcodes.js
lib/resources/zipcodes.spec.js
lib/routes.js

Criei um resource para comunicar com o endpoint `/zipcodes`, passando no `body.zipcode` um CEP válido. Podem revisar?
Obrigado!

Add zipcodes resource

---

README.md

task: Update logo

---

lib/index.js

Fixes https://github.com/pagarme/pagarme-js/issues/95

index: replace Object.assign with ramda's merge

---

.travis.yml

Node 8 will enter the LTS stage in the next week, it is important to consider this on the CI environment :)

Add travis job for node 8

---

lib/client/index.js
lib/client/strategies/encryption.js
lib/resources/security.js
lib/validations/validate/card/cardNumber.js
lib/validations/validate/card/cvv.js
lib/validations/validate/cnpjAndCpf.js

General code improvements.
- Remove boilerplate from `cardNumber`
- Use Bluebird 3 `catch` on `encryption`
- :white_check_mark: linter is passing
- :white_check_mark: tests are passing
- :white_check_mark: @GitCop no longer being mad
This time I'll not be git-copped!

General code improvements

---

lib/resources/session.spec.js

closes #34
I first wrote some failing tests to understand what was being returned and started fixing it
😁

session-test: add tests for session

---

.travis.yml
lib/errors.js
package.json

This fixes #109 by using a proper error message. 

Fix error interface

---

lib/resources/balanceOperations.js
lib/resources/bulkAnticipations.js

This PR fix some small problems related to query parameters

Fix GET body in balance operations and bulk anticipations

---

lib/resources/balanceOperations.js

Closes #125 
Add url params to findRecipients in balance operations

balance-operations: fix findRecipients params

---

lib/resources/balanceOperations.js
lib/resources/balanceOperations.spec.js

add query string parameters to GET `/balance/operations/days`

balance-operations: add body to day query

---

lib/resources/antifraudAnalyses.js
lib/resources/antifraudAnalyses.spec.js
lib/routes.js

This PR add a new route to create antifraud analyses.

antifraud-analyses: add create route

---

lib/request.js

adding in request a content-type validation in case of xlsx file format  and adding the ArrayBuffer to preserve the binary data

request: add xlsx content-type file format

---

.travis.yml
lib/client/strategies/api.js
lib/resources/acquirers.spec.js
lib/resources/acquirersConfigurations.spec.js
lib/resources/bankAccounts.spec.js
lib/resources/bulkAnticipations.spec.js
lib/resources/cards.spec.js
lib/resources/company.spec.js
lib/resources/index.spec.js
lib/resources/security.spec.js
lib/resources/session.spec.js
lib/resources/subscriptions.spec.js
lib/resources/zipcodes.spec.js
lib/validations/index.spec.js
package.json
test/echoServer/index.js
test/runTest.js

This PR:
- adds `lint` task.
- adds `yarn lint` in Travis ci build
- fixes lint errors
resolves #143

chore: add lint test

---

lib/request.js
lib/version.js
package.json

With this header, we will be able to obtain metrics about our SDK usage.

add X-PagarMe-User-Agent header to requests

---

lib/resources/index.js
lib/resources/orders.js
lib/resources/orders.spec.js
lib/routes.js
package-lock.json

Criar o recurso `orders` com o método `all`.
Write a brief and explicative description of your pull request.

resources: add orders "all" route

---

README.md

Updates the README.md with the newest version of the CDN link to the browser version.

Update CDN link

---

lib/resources/index.js
lib/resources/versions.js
lib/resources/versions.spec.js
lib/routes.js

This PR add a `versions` resource to client, with this I can list all available versions from API.

api: add versions resource to client

---

README.md

This pull request updates cdn link in readme.md,

chore: update readme cdn link to 4.4

---

lib/resources/index.js
lib/resources/reprocessedTransactions.js
lib/resources/reprocessedTransactions.spec.js
lib/routes.js

Add new route to search for reprocessed transactions.
closes https://github.com/pagarme/pagarme-js/issues/198

reprocessedTransactions: add new route

---

lib/resources/companySegments.js
lib/resources/companySegments.spec.js
lib/resources/index.js
lib/routes.js

add a route to list the company segments
[x] Resolves #231 

companySegments: add route

---

.circleci/config.yml
package.json
test/echoServer/index.js
yarn.lock

Este pr adiciona a configuração do circle ci ao projeto
- verificar se o que está rodando no circle ci faz sentido com a config existente do travis
- verificar se está passando no circle ci
resolves https://github.com/pagarme/tecnologia-vendas/issues/855

Circleci project setup

---

README.md

este pr atualiza o link da cdn no readme para versão 4.8.x

readme: update cdn link

---

README.md

https://github.com/pagarme/pagarme-js/pull/255

readme: update version v4.9.0

---

README.md

atualiza link da cdn no readme

readme: update cdn link to 4.10

---

.circleci/config.yml
README.md
package.json
sonar-project.properties

Adiciona a análise do sonar: https://sonarcloud.io/dashboard?id=pagarme-js
Adicionei as badges tb:

CI: add sonar analysis

---

lib/resources/credit.js
lib/resources/credit.spec.js
lib/resources/index.js
lib/routes.js

Este PR tem como objetivo adicionar as rotas da API de crédito.
Resumo dos endpoints: 
**Todos as rotas tem o prefixo `/credit/`**
| Rota |  Descrição | 
|---|---|
| `GET /credit_lines` | Lista as linhas de crédito  | 
| `GET /credit_lines/:creditLineId/proposals/:proposalId`  |  Obtem detalhes da proposta |  
| `GET /credit_lines/:creditLineId/proposals/:proposalId/settlement_forecast` | Obtem a previsão de liquidação do empréstimo |
| `GET /loans` | Lista os emprestimos  | 
| `GET /loans/:loanId` | Obtem detalhes do empréstimo | 
| `GET /loans/:loanId/statements/daily` | Obtem histórico de pagamentos diário |
| `GET /loans/:loanId/statements/monthly` | Obtem histórico de pagamentos mensal |
|`POST /credit_lines/:creditLineId/proposals`| Cria uma proposta baseada numa linha de crédito | …

[FCRED-165] Adicionar rotas da API de crédito

---

package.json

atualiza versão do pacote para 4.19.0

update to 4.19.0
